# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='saida',
            field=models.DateTimeField(blank=True, verbose_name='saida'),
        ),
    ]
