# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0003_auto_20170130_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkingHours',
            new_name='TurnoDeTrabalho',
        ),
    ]
