# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 22:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0004_auto_20170131_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ramal', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Numero de telefone precisa estar no formato: XXXX ', regex='^\\d{4}$')])),
            ],
        ),
    ]
