# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0005_ramalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='lotacao',
            field=models.CharField(default='lotação', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estagiario',
            name='ramal',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='empregado.RamalModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='lotacao',
            field=models.CharField(default='lotação', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='ramal',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='empregado.RamalModel'),
            preserve_default=False,
        ),
    ]
