# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0007_auto_20170208_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
