# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregado', '0008_auto_20170209_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoDeHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_de_horas', models.DurationField(default=0)),
                ('saldo_de_horas_mes_atual', models.DurationField(default=0)),
                ('estagiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empregado.Estagiario')),
            ],
        ),
    ]
